version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: retro-mike-kheavyhash-bridge_web_1
      APP_PORT: 8080
    
  server:
    image: theretromike/stratums:kHeavyHash
    user: "1000:1000"
    init: true
    entrypoint: "/app --stratum :5001"
  web:
    image: amir20/dozzle:v8.12.8@sha256:8ff3115c9c9dd7576839df6f2575de345ca7cafa398cf2496f1f19c31d862ac1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - server
