#!/usr/bin/env bash
set -euo pipefail

PM="/home/umbrel/umbrel/app-data/retro-mike-miningcore/scripts/pool-manager.sh"
[ -x "${PM}" ] || exit 0

ARGS=( register-bitcoin
  --pool-id "bch"
  --coin "bitcoin-cash"
  --app-id "retro-mike-bch-node"
  --rpc-port "9002"
  --zmq-port "7002"
  --stratum-port "6002"
  --daemon-host "retro-mike-bch-node_node_1"
)

ARGS+=( --address-type "bcash" )
ARGS+=( --getnewaddress-params '[]' )
"${PM}" "${ARGS[@]}"
