version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-dozzle_web_1
      APP_PORT: 8080

  web:
    image: amir20/dozzle:v8.12.8@sha256:8ff3115c9c9dd7576839df6f2575de345ca7cafa398cf2496f1f19c31d862ac1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
