#!/usr/bin/env bash
set -euo pipefail
if [ ! -x "/home/umbrel/umbrel/app-data/retro-mike-miningcore/scripts/pool-manager.sh" ]; then
  exit 0
fi

"/home/umbrel/umbrel/app-data/retro-mike-miningcore/scripts/pool-manager.sh" register-bitcoin   --pool-id "btc"   --coin "bitcoin"   --app-id "retro-mike-btc-node"   --rpc-port "9004"   --zmq-port "7004"   --stratum-port "6004"   --daemon-host "retro-mike-btc-node_node_1"
