#!/usr/bin/env bash
set -euo pipefail
if [ ! -x "/home/umbrel/umbrel/app-data/retro-mike-miningcore/scripts/pool-manager.sh" ]; then
  exit 0
fi

"/home/umbrel/umbrel/app-data/retro-mike-miningcore/scripts/pool-manager.sh" register-bitcoin   --pool-id "vtc"   --coin "vertcoin"   --app-id "retro-mike-vtc-node"   --rpc-port "9008"   --zmq-port "7008"   --stratum-port "6008"   --daemon-host "retro-mike-vtc-node_node_1"
