// This file is auto-generated by entrypoint.sh at container startup
window.POOL_CONFIG = {
    apiUrl: "/api",
    poolName: "Umbrel LTC+DOGE Pool",
    stratumHost: "your-umbrel-ip",
    stratumPort: 3333,
    ltcAddress: "not-configured",
    dogeAddress: "not-configured"
};
